kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podlabeler
rules:
- apiGroups: [""]
  resources:
  - pods
  - configmaps
  verbs: ["*"]
- apiGroups: ["podlabeler.k8s.carsonoid.net"]
  resources:
  - "*"
  verbs: ["*"]
