apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-admin
  namespace: kube-public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-admin
rules:
- apiGroups:
  - provisioner.k8s.carsonoid.net
  resources:
  - workshopattendees
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-admin
subjects:
- kind: ServiceAccount
  name: workshop-admin
  namespace: kube-public
