/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/carsonoid/kube-crds-and-controllers/controllers/workshop-provisioner/pkg/apis/provisioner/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WorkshopAttendeeLister helps list WorkshopAttendees.
type WorkshopAttendeeLister interface {
	// List lists all WorkshopAttendees in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.WorkshopAttendee, err error)
	// Get retrieves the WorkshopAttendee from the index for a given name.
	Get(name string) (*v1alpha1.WorkshopAttendee, error)
	WorkshopAttendeeListerExpansion
}

// workshopAttendeeLister implements the WorkshopAttendeeLister interface.
type workshopAttendeeLister struct {
	indexer cache.Indexer
}

// NewWorkshopAttendeeLister returns a new WorkshopAttendeeLister.
func NewWorkshopAttendeeLister(indexer cache.Indexer) WorkshopAttendeeLister {
	return &workshopAttendeeLister{indexer: indexer}
}

// List lists all WorkshopAttendees in the indexer.
func (s *workshopAttendeeLister) List(selector labels.Selector) (ret []*v1alpha1.WorkshopAttendee, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WorkshopAttendee))
	})
	return ret, err
}

// Get retrieves the WorkshopAttendee from the index for a given name.
func (s *workshopAttendeeLister) Get(name string) (*v1alpha1.WorkshopAttendee, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("workshopattendee"), name)
	}
	return obj.(*v1alpha1.WorkshopAttendee), nil
}
